

DROP TABLE IF EXISTS `CONNECTION`;
DROP TABLE IF EXISTS `METADATA`;


CREATE TABLE `CONNECTION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CONN_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  
  PRIMARY KEY (`ID`)
)

CREATE TABLE `METADATA` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MSG_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `LOCATION` VARCHAR(50),
  PRIMARY KEY (`ID`)
)
