

DROP TABLE IF EXISTS `CONNECTION`;
DROP TABLE IF EXISTS `METADATA`;


CREATE TABLE `CONNECTION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CONN_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  
  PRIMARY KEY (`ID`)
)

CREATE TABLE `MESSAGES` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MSG_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `LAT` FLOAT,
  `LNG` FLOAT,
  `MESSAGE` VARCHAR(512),
  `USER`, VARCHAR(64),
  PRIMARY KEY (`ID`)
)
